---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: flux-system
spec:
  releaseName: aws-load-balancer-controller
  targetNamespace: production
  upgrade:
    preserveValues: false
  install:
    createNamespace: true
  interval: 5m
  chart:
    spec:
      chart: aws-load-balancer-controller
      version: '1.2.5'
      sourceRef:
        kind: HelmRepository
        name: eks-charts
        namespace: flux-system
      interval: 1m
  values:
    fullnameOverride: aws-load-balancer-controller
    replicaCount: 2
    clusterName: boosta-dev
    rbac:
      create: true
    podSecurityContext:
      fsGroup: 65534
    securityContext:
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      allowPrivilegeEscalation: false
    terminationGracePeriodSeconds: 10
    priorityClassName: system-cluster-critical
    ingressClass: alb
    enablePodReadinessGateInject: true
    ## enableShield: true
    ## enableWaf: true
    ## enableWafv2: true
    ## defaultSSLPolicy: ELBSecurityPolicy-TLS-1-1-2017-01
